#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

repo_root="$(cd $(dirname ${BASH_SOURCE[0]})/.. && pwd)"

cd ${repo_root}
git submodule update --init --recursive

if [ "$(uname -s)" == "Darwin" ]
then
  formulae=$(brew list)
  taps=$(brew tap)
  casks=$(brew cask list)

  for f in hub go jq \
    kubernetes-cli awscli \
    vault packer tfenv \
    gnupg tmux vim \
    ansible
  do
    if ! echo ${formulae} | grep -q "${f}"
    then
      brew install ${f}
    fi
  done

  for t in homebrew/cask-fonts
  do
    if ! echo ${taps} | grep -q "${t}"
    then
      brew tap ${t}
    fi
  done

  for c in amethyst atom slack font-inconsolata
  do
    if ! echo ${casks} | grep -q "${c}"
    then
      brew cask install ${c}
    fi
  done
fi

[ -e ${HOME}/.oh-my-zsh ] ||
git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git "${HOME}/.oh-my-zsh"

[ "$(basename ${SHELL})" == "zsh" ] || chsh -s $(which zsh)
